export const config = {
  CLIENT_ID: '2UHO4RL3ISWLVGGU1RMBS500G1YLY5CRKFYUG0DBEAQOFT5A',
  CLIENT_SECRET: '4KMTRNSGKUBK4PNS0FMFQKNBFYW50VWBPUUKRYPTWIEOUAYW',
  GOOGLE_API_KEY: 'AIzaSyAccLDIKvRZoqvfAIsJvidZmRQkbobvlEw',
  PROXY_URL: 'https://cors-anywhere.herokuapp.com/'
};